Add typescript (#34)
Depends on #33 

- Add typescript + some type definitions as `devDependencies`
- Change the file extensions to `.tsx` from `.jsx` 
- Update makefile so that we can build and run type checks

This does not validate type checking yet, just gets the tooling in
place.

```
❯ make validate-typescript
cd desktop-exporter; npx tsc --noEmit
app/components/header.tsx:12:24 - error TS7006: Parameter 'props' implicitly has an 'any' type.

12 export function Header(props) {
                          ~~~~~

app/error-page.tsx:13:13 - error TS18046: 'error' is of type 'unknown'.

13         <i>{error.statusText || error.message}</i>
               ~~~~~

app/error-page.tsx:13:33 - error TS18046: 'error' is of type 'unknown'.

13         <i>{error.statusText || error.message}</i>
                                   ~~~~~

app/main.tsx:27:25 - error TS2345: Argument of type 'HTMLElement | null' is not assignable to parameter of type 'Element | DocumentFragment'.
  Type 'null' is not assignable to type 'Element | DocumentFragment'.

27 const root = createRoot(container);
                           ~~~~~~~~~

app/routes/main-view.tsx:12:16 - error TS7031: Binding element 'index' implicitly has an 'any' type.

12 function Row({ index, style, data }) {
                  ~~~~~

app/routes/main-view.tsx:12:23 - error TS7031: Binding element 'style' implicitly has an 'any' type.

12 function Row({ index, style, data }) {
                         ~~~~~

app/routes/main-view.tsx:12:30 - error TS7031: Binding element 'data' implicitly has an 'any' type.

12 function Row({ index, style, data }) {
                                ~~~~

app/routes/main-view.tsx:23:18 - error TS7006: Parameter 'props' implicitly has an 'any' type.

23 function Sidebar(props) {
                    ~~~~~

app/routes/main-view.tsx:37:11 - error TS2339: Property 'traceSummaries' does not exist on type 'unknown'.

37   const { traceSummaries } = useLoaderData();
             ~~~~~~~~~~~~~~

app/routes/trace-view.tsx:7:37 - error TS7031: Binding element 'params' implicitly has an 'any' type.

7 export async function traceLoader({ params }) {
                                      ~~~~~~

app/routes/trace-view.tsx:13:25 - error TS7031: Binding element 'index' implicitly has an 'any' type.

13 function WaterfallRow({ index, style, data }) {
                           ~~~~~

app/routes/trace-view.tsx:13:32 - error TS7031: Binding element 'style' implicitly has an 'any' type.

13 function WaterfallRow({ index, style, data }) {
                                  ~~~~~

app/routes/trace-view.tsx:13:39 - error TS7031: Binding element 'data' implicitly has an 'any' type.

13 function WaterfallRow({ index, style, data }) {
                                         ~~~~

app/routes/trace-view.tsx:34:24 - error TS7006: Parameter 'props' implicitly has an 'any' type.

34 function WaterfallView(props) {
                          ~~~~~

app/routes/trace-view.tsx:49:21 - error TS7006: Parameter 'props' implicitly has an 'any' type.

49 function DetailView(props) {
                       ~~~~~

app/routes/trace-view.tsx:69:5 - error TS18046: 'traceData' is of type 'unknown'.

69     traceData.spans[0].spanID,
       ~~~~~~~~~

app/routes/trace-view.tsx:74:23 - error TS18046: 'traceData' is of type 'unknown'.

74     setSelectedSpanID(traceData.spans[0].spanID);
                         ~~~~~~~~~

app/routes/trace-view.tsx:77:24 - error TS18046: 'traceData' is of type 'unknown'.

77   const selectedSpan = traceData.spans.find(
                          ~~~~~~~~~

app/routes/trace-view.tsx:78:6 - error TS7006: Parameter 'span' implicitly has an 'any' type.

78     (span) => span.spanID === selectedSpanID,
        ~~~~

app/routes/trace-view.tsx:83:24 - error TS18046: 'traceData' is of type 'unknown'.

83       <Header traceID={traceData.traceID} />
                          ~~~~~~~~~

app/routes/trace-view.tsx:85:16 - error TS18046: 'traceData' is of type 'unknown'.

85         spans={traceData.spans}
                  ~~~~~~~~~


Found 21 errors in 5 files.

Errors  Files
     1  app/components/header.tsx:12
     2  app/error-page.tsx:13
     1  app/main.tsx:27
     5  app/routes/main-view.tsx:12
    12  app/routes/trace-view.tsx:7
make: *** [validate-typescript] Error 2
```